package com.example.coffeecraft.Utils;


import java.util.HashMap;
import java.util.Map;

public class GetCountryCode {

    Map<String, String> nameCodeMap;

    public GetCountryCode(){
        nameCodeMap = new HashMap<>();

        nameCodeMap.put("Afghanistan", "AF");
        nameCodeMap.put("Åland Islands", "AX");
        nameCodeMap.put("Albania", "AL");
        nameCodeMap.put("Algeria", "DZ");
        nameCodeMap.put("American Samoa", "AS");
        nameCodeMap.put("Andorra", "AD");
        nameCodeMap.put("Angola", "AO");
        nameCodeMap.put("Anguilla", "AI");
        nameCodeMap.put("Antarctica", "AQ");
        nameCodeMap.put("Antigua and Barbuda", "AG");
        nameCodeMap.put("Argentina", "AR");
        nameCodeMap.put("Armenia", "AM");
        nameCodeMap.put("Aruba", "AW");
        nameCodeMap.put("Australia", "AU");
        nameCodeMap.put("Austria", "AT");
        nameCodeMap.put("Azerbaijan", "AZ");
        nameCodeMap.put("Bahamas", "BS");
        nameCodeMap.put("Bahrain", "BH");
        nameCodeMap.put("Bangladesh", "BD");
        nameCodeMap.put("Barbados", "BB");
        nameCodeMap.put("Belarus", "BY");
        nameCodeMap.put("Belgium", "BE");
        nameCodeMap.put("Belize", "BZ");
        nameCodeMap.put("Benin", "BJ");
        nameCodeMap.put("Bermuda", "BM");
        nameCodeMap.put("Bhutan", "BT");
        nameCodeMap.put("Bolivia", "BO");
        nameCodeMap.put("Bosnia and Herzegovina", "BA");
        nameCodeMap.put("Botswana", "BW");
        nameCodeMap.put("Bouvet Island", "BV");
        nameCodeMap.put("Brazil", "BR");
        nameCodeMap.put("British Indian Ocean Territory", "IO");
        nameCodeMap.put("Brunei Darussalam", "BN");
        nameCodeMap.put("Bulgaria", "BG");
        nameCodeMap.put("Burkina Faso", "BF");
        nameCodeMap.put("Burundi", "BI");
        nameCodeMap.put("Cambodia", "KH");
        nameCodeMap.put("Cameroon", "CM");
        nameCodeMap.put("Canada", "CA");
        nameCodeMap.put("Cape Verde", "CV");
        nameCodeMap.put("Cayman Islands", "KY");
        nameCodeMap.put("Central African Republic", "CF");
        nameCodeMap.put("Chad", "TD");
        nameCodeMap.put("Chile", "CL");
        nameCodeMap.put("China", "CN");
        nameCodeMap.put("Christmas Island", "CX");
        nameCodeMap.put("Colombia", "CO");
        nameCodeMap.put("Comoros", "KM");
        nameCodeMap.put("Congo", "CG");
        nameCodeMap.put("Congo, the Democratic Republic of the", "CD");
        nameCodeMap.put("Cook Islands", "CK");
        nameCodeMap.put("Costa Rica", "CR");
        nameCodeMap.put("Côte d'Ivoire", "CI");
        nameCodeMap.put("Croatia", "HR");
        nameCodeMap.put("Cuba", "CU");
        nameCodeMap.put("Curaçao", "CW");
        nameCodeMap.put("Cyprus", "CY");
        nameCodeMap.put("Czech Republic", "CZ");
        nameCodeMap.put("Denmark", "DK");
        nameCodeMap.put("Djibouti", "DJ");
        nameCodeMap.put("Dominica", "DM");
        nameCodeMap.put("Dominican Republic", "DO");
        nameCodeMap.put("Ecuador", "EC");
        nameCodeMap.put("Egypt", "EG");
        nameCodeMap.put("El Salvador", "SV");
        nameCodeMap.put("Equatorial Guinea", "GQ");
        nameCodeMap.put("Eritrea", "ER");
        nameCodeMap.put("Estonia", "EE");
        nameCodeMap.put("Ethiopia", "ET");
        nameCodeMap.put("Falkland Islands (Malvinas)", "FK");
        nameCodeMap.put("Faroe Islands", "FO");
        nameCodeMap.put("Fiji", "FJ");
        nameCodeMap.put("Finland", "FI");
        nameCodeMap.put("France", "FR");
        nameCodeMap.put("French Guiana", "GF");
        nameCodeMap.put("French Polynesia", "PF");
        nameCodeMap.put("French Southern Territories", "TF");
        nameCodeMap.put("Gabon", "GA");
        nameCodeMap.put("Gambia", "GM");
        nameCodeMap.put("Georgia", "GE");
        nameCodeMap.put("Germany", "DE");
        nameCodeMap.put("Ghana", "GH");
        nameCodeMap.put("Gibraltar", "GI");
        nameCodeMap.put("Greece", "GR");
        nameCodeMap.put("Greenland", "GL");
        nameCodeMap.put("Grenada", "GD");
        nameCodeMap.put("Guadeloupe", "GP");
        nameCodeMap.put("Guam", "GU");
        nameCodeMap.put("Guatemala", "GT");
        nameCodeMap.put("Guernsey", "GG");
        nameCodeMap.put("Guinea", "GN");
        nameCodeMap.put("Guinea-Bissau", "GW");
        nameCodeMap.put("Guyana", "GY");
        nameCodeMap.put("Haiti", "HT");
        nameCodeMap.put("Heard Island and McDonald Islands", "HM");
        nameCodeMap.put("Holy See (Vatican City State)", "VA");
        nameCodeMap.put("Honduras", "HN");
        nameCodeMap.put("Hong Kong", "HK");
        nameCodeMap.put("Hungary", "HU");
        nameCodeMap.put("Iceland", "IS");
        nameCodeMap.put("India", "IN");
        nameCodeMap.put("Indonesia", "ID");
        nameCodeMap.put("Iran, Islamic Republic of", "IR");
        nameCodeMap.put("Iraq", "IQ");
        nameCodeMap.put("Ireland", "IE");
        nameCodeMap.put("Isle of Man", "IM");
        nameCodeMap.put("Israel", "IL");
        nameCodeMap.put("Italy", "IT");
        nameCodeMap.put("Jamaica", "JM");
        nameCodeMap.put("Japan", "JP");
        nameCodeMap.put("Jersey", "JE");
        nameCodeMap.put("Jordan", "JO");
        nameCodeMap.put("Kazakhstan", "KZ");
        nameCodeMap.put("Kenya", "KE");
        nameCodeMap.put("Kiribati", "KI");
        nameCodeMap.put("Korea, Democratic People's Republic of", "KP");
        nameCodeMap.put("Korea, Republic of", "KR");
        nameCodeMap.put("Kuwait", "KW");
        nameCodeMap.put("Kyrgyzstan", "KG");
        nameCodeMap.put("Lao People's Democratic Republic", "LA");
        nameCodeMap.put("Latvia", "LV");
        nameCodeMap.put("Lebanon", "LB");
        nameCodeMap.put("Lesotho", "LS");
        nameCodeMap.put("Liberia", "LR");
        nameCodeMap.put("Libya", "LY");
        nameCodeMap.put("Liechtenstein", "LI");
        nameCodeMap.put("Lithuania", "LT");
        nameCodeMap.put("Luxembourg", "LU");
        nameCodeMap.put("Macao", "MO");
        nameCodeMap.put("Macedonia, the Former Yugoslav Republic of", "MK");
        nameCodeMap.put("Madagascar", "MG");
        nameCodeMap.put("Malawi", "MW");
        nameCodeMap.put("Malaysia", "MY");
        nameCodeMap.put("Maldives", "MV");
        nameCodeMap.put("Mali", "ML");
        nameCodeMap.put("Malta", "MT");
        nameCodeMap.put("Marshall Islands", "MH");
        nameCodeMap.put("Martinique", "MQ");
        nameCodeMap.put("Mauritania", "MR");
        nameCodeMap.put("Mauritius", "MU");
        nameCodeMap.put("Mayotte", "YT");
        nameCodeMap.put("Mexico", "MX");
        nameCodeMap.put("Micronesia, Federated States of", "FM");
        nameCodeMap.put("Moldova, Republic of", "MD");
        nameCodeMap.put("Monaco", "MC");
        nameCodeMap.put("Mongolia", "MN");
        nameCodeMap.put("Montenegro", "ME");
        nameCodeMap.put("Montserrat", "MS");
        nameCodeMap.put("Morocco", "MA");
        nameCodeMap.put("Mozambique", "MZ");
        nameCodeMap.put("Myanmar", "MM");
        nameCodeMap.put("Namibia", "nan");
        nameCodeMap.put("Nauru", "NR");
        nameCodeMap.put("Nepal", "NP");
        nameCodeMap.put("Netherlands", "NL");
        nameCodeMap.put("New Caledonia", "NC");
        nameCodeMap.put("New Zealand", "NZ");
        nameCodeMap.put("Nicaragua", "NI");
        nameCodeMap.put("Niger", "NE");
        nameCodeMap.put("Nigeria", "NG");
        nameCodeMap.put("Niue", "NU");
        nameCodeMap.put("Norfolk Island", "NF");
        nameCodeMap.put("Northern Mariana Islands", "MP");
        nameCodeMap.put("Norway", "NO");
        nameCodeMap.put("Oman", "OM");
        nameCodeMap.put("Pakistan", "PK");
        nameCodeMap.put("Palau", "PW");
        nameCodeMap.put("Palestine, State of", "PS");
        nameCodeMap.put("Panama", "PA");
        nameCodeMap.put("Papua New Guinea", "PG");
        nameCodeMap.put("Paraguay", "PY");
        nameCodeMap.put("Peru", "PE");
        nameCodeMap.put("Philippines", "PH");
        nameCodeMap.put("Pitcairn", "PN");
        nameCodeMap.put("Poland", "PL");
        nameCodeMap.put("Portugal", "PT");
        nameCodeMap.put("Puerto Rico", "PR");
        nameCodeMap.put("Qatar", "QA");
        nameCodeMap.put("Réunion", "RE");
        nameCodeMap.put("Romania", "RO");
        nameCodeMap.put("Russian Federation", "RU");
        nameCodeMap.put("Rwanda", "RW");
        nameCodeMap.put("Saint Barthélemy", "BL");
        nameCodeMap.put("Saint Helena, Ascension and Tristan da Cunha", "SH");
        nameCodeMap.put("Saint Kitts and Nevis", "KN");
        nameCodeMap.put("Saint Lucia", "LC");
        nameCodeMap.put("Saint Martin (French part)", "MF");
        nameCodeMap.put("Saint Pierre and Miquelon", "PM");
        nameCodeMap.put("Saint Vincent and the Grenadines", "VC");
        nameCodeMap.put("Samoa", "WS");
        nameCodeMap.put("San Marino", "SM");
        nameCodeMap.put("Sao Tome and Principe", "ST");
        nameCodeMap.put("Saudi Arabia", "SA");
        nameCodeMap.put("Senegal", "SN");
        nameCodeMap.put("Serbia", "RS");
        nameCodeMap.put("Seychelles", "SC");
        nameCodeMap.put("Sierra Leone", "SL");
        nameCodeMap.put("Singapore", "SG");
        nameCodeMap.put("Sint Maarten (Dutch part)", "SX");
        nameCodeMap.put("Slovakia", "SK");
        nameCodeMap.put("Slovenia", "SI");
        nameCodeMap.put("Solomon Islands", "SB");
        nameCodeMap.put("Somalia", "SO");
        nameCodeMap.put("South Africa", "ZA");
        nameCodeMap.put("South Georgia and the South Sandwich Islands", "GS");
        nameCodeMap.put("South Sudan", "SS");
        nameCodeMap.put("Spain", "ES");
        nameCodeMap.put("Sri Lanka", "LK");
        nameCodeMap.put("Sudan", "SD");
        nameCodeMap.put("Suriname", "SR");
        nameCodeMap.put("Svalbard and Jan Mayen", "SJ");
        nameCodeMap.put("Swaziland", "SZ");
        nameCodeMap.put("Sweden", "SE");
        nameCodeMap.put("Switzerland", "CH");
        nameCodeMap.put("Syrian Arab Republic", "SY");
        nameCodeMap.put("Taiwan, Province of China", "TW");
        nameCodeMap.put("Tajikistan", "TJ");
        nameCodeMap.put("Tanzania, United Republic of", "TZ");
        nameCodeMap.put("Thailand", "TH");
        nameCodeMap.put("Timor-Leste", "TL");
        nameCodeMap.put("Togo", "TG");
        nameCodeMap.put("Tokelau", "TK");
        nameCodeMap.put("Tonga", "TO");
        nameCodeMap.put("Trinidad and Tobago", "TT");
        nameCodeMap.put("Tunisia", "TN");
        nameCodeMap.put("Turkey", "TR");
        nameCodeMap.put("Turkmenistan", "TM");
        nameCodeMap.put("Turks and Caicos Islands", "TC");
        nameCodeMap.put("Tuvalu", "TV");
        nameCodeMap.put("Uganda", "UG");
        nameCodeMap.put("Ukraine", "UA");
        nameCodeMap.put("United Arab Emirates", "AE");
        nameCodeMap.put("United Kingdom", "GB");
        nameCodeMap.put("United States", "US");
        nameCodeMap.put("United States Minor Outlying Islands", "UM");
        nameCodeMap.put("Uruguay", "UY");
        nameCodeMap.put("Uzbekistan", "UZ");
        nameCodeMap.put("Vanuatu", "VU");
        nameCodeMap.put("Venezuela, Bolivarian Republic of", "VE");
        nameCodeMap.put("Viet Nam", "VN");
        nameCodeMap.put("Virgin Islands, British", "VG");
        nameCodeMap.put("Virgin Islands, U.S.", "VI");
        nameCodeMap.put("Wallis and Futuna", "WF");
        nameCodeMap.put("Western Sahara", "EH");
        nameCodeMap.put("Yemen", "YE");
        nameCodeMap.put("Zambia", "ZM");
        nameCodeMap.put("Zimbabwe", "ZW");
    }

    public String getCode(String country)  {
        return nameCodeMap.get(country);
    }

}
